### ISSUE TITLE
Feature Request: More information on contributing

### ISSUE THREAD

**Issue by therealbnut** [scottjenson/Tech-Volunteering#1]
Thanks for putting this together, I hope that it grows and is useful for more people!

In order to lower the barrier to people contributing, what do you think about adding a license and a small section in the readme welcoming contributions, and  if putting up a PR is the best way? License wise I think Github has templates, but some kind of CC one might work well: https://choosealicense.com/non-software/

**Comment by scottjenson** [comment]
Great points, I'll change the PR only approach to 'just email
***@***.***' so it's easier.

I can't see how to change the License. I didn't add one at the beginning
and I can't find anything in the settings to add one. Do you know how to do
that?

Thanks,

Scott

**Comment by therealbnut** [comment]
To add a license you just need a file called `LICENSE.md` or similar, and if it's a common one then it should be picked up by github and it will put the appropriate metadata in place. There's plenty of examples of CC ones here, you just need to copy whichever of those files suits your purposes (and you can keep the filename of those): https://github.com/santisoler/cc-licenses

Can I suggest that if you want to allow email contributions you also say you're open to PRs? I think a PR will be many people's preferred method, it also gives a way to openly iterate on feedback, see if something has already been suggested but not merged, and if people wanted to help review them for you then it's all in one place :)

**Comment by therealbnut** [comment]
I'm very sorry for the misunderstanding, I just realised that you _did_ have something about PRs on the README, I just failed to read it. I'm used to seeing a `# Contributing` section, and must have skimmed past it.

**Comment by scottjenson** [comment]
THanks for all the help just added a Contributing section (as that seems to
be the accepted pattern) making it clear both Email AND PRs were welcome,
and finally adding a CC 1.0 Universal license to it. I hope we're good now.

**Comment by therealbnut** [comment]
Looks great, thanks!
